---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitea-docker-credentials.yaml
  - task-git-clone.yaml
  - task-kaniko.yaml
  - pipeline-build-push.yaml
  - triggers.yaml
