---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: alucard-web
  namespace: flux-system
spec:
  image: docker.io/spencerrung/alucard-web
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nova
  namespace: flux-system
spec:
  image: docker.io/spencerrung/nova
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: finale
  namespace: flux-system
spec:
  image: docker.io/spencerrung/finale
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: breathe
  namespace: flux-system
spec:
  image: docker.io/spencerrung/breathe
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: resume
  namespace: flux-system
spec:
  image: docker.io/spencerrung/resume
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: daily-news
  namespace: flux-system
spec:
  image: docker.io/spencerrung/daily-news
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: aimtrix
  namespace: flux-system
spec:
  image: docker.io/spencerrung/aimtrix
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: newhope-web
  namespace: flux-system
spec:
  image: docker.io/spencerrung/newhope-web
  interval: 15m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: newhope-views
  namespace: flux-system
spec:
  image: docker.io/spencerrung/newhope-views
  interval: 15m
