---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alucard-web
  namespace: alucard-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - alucard.dev
      secretName: alucard-web-tls
  rules:
    - host: alucard.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alucard-web
                port:
                  name: http
