---
# Stateless static sites.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../alucard-web
  - ../../nova
  - ../../finale
  - ../../breathe
  - ../../resume
  - ../../daily-news
