---
# Stateless static sites.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../alucard-web
  - ../../simple-cookbook
  - ../../nova
  - ../../finale
  - ../../breathe
