---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: matrix
  namespace: flux-system
spec:
  type: matrix
  address: http://synapse.matrix.svc.cluster.local:8008
  channel: "!blIpnGzhOAWXoAkiSG:alucard.dev"
  secretRef:
    name: flux-matrix-token
