---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/
  - tf-controller/
  - vault/
  - external-secrets/
# Add more infrastructure components as needed
# Example:
# - traefik/
# - cert-manager/
