---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../alucard-web  # Alucard.dev static website
  - ../../simple-cookbook  # Simple-Cookbook.com static website
  - ../../matrix  # Matrix (Synapse) homeserver + Element web
# Add homelab-specific patches and resources here
