---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-test-secret
  namespace: eso-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: synced-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: test
        property: username
    - secretKey: password
      remoteRef:
        key: test
        property: password
