---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hashicorp.yaml
  - external-secrets.yaml
  - tofu-controller.yaml
  - authentik.yaml
  - jetstack.yaml
  - traefik.yaml
  - gitea.yaml
