---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - externalsecrets.yaml
  - postgresql.yaml
  - release.yaml
  - ingress.yaml
  - users-groups-blueprint.yaml
  - username-scope-mapping-blueprint.yaml
  - gitea-oidc-blueprint.yaml
