apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - resources.yaml
configMapGenerator:
  - name: bsky-notifier-code
    files:
      - watcher.py
  - name: bsky-notifier-rules
    files:
      - rules.json
