---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespace + secret plumbing
  - namespace.yaml
  - externalsecrets.yaml
  # Database
  - postgresql.yaml
  - networkpolicy.yaml
  # Synapse homeserver
  - synapse-config.yaml
  - synapse-pvc.yaml
  - synapse-deployment.yaml
  - synapse-service.yaml
  - synapse-ingress.yaml
  - wellknown-server.yaml
  - wellknown-ingress.yaml
  # Element web client
  - element-config.yaml
  - element-deployment.yaml
  - element-service.yaml
  - element-ingress.yaml
  # Cinny web client
  - cinny-config.yaml
  - cinny-deployment.yaml
  - cinny-service.yaml
  - cinny-ingress.yaml
